import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				<nav className="py-2 sticky bottom-0 bg-white border-t-2">
					<ul className="flex justify-center gap-6">
						<li>
							<Link href={`/days/${new Date().toISOString().substring(0, 10)}`}>Сегодня</Link>
						</li>
						<li>
							<Link href="/days/create">Создать</Link>
						</li>
						<li>
							<Link href="/days">Все дни</Link>
						</li>
					</ul>
				</nav>
			</body>
		</html>
	)
}
